# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Geo2Local
                                 A QGIS plugin
 This plugin converts coordinates
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-04-19
        copyright            : (C) 2018 by Diego Moreira Carvalho/Curupira Tecnologia
        email                : diego@curupiratecnologia.com.br
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Geo2Local class from file Geo2Local.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .geo2local import Geo2Local
    return Geo2Local(iface)
